### ISSUE TITLE
4.6.4 OFFENLEGUNG DER QUALITÄTSKONTROLLPLÄNE nachreichen

### ISSUE THREAD

**Issue by JanSutmoeller** [JanSutmoeller/HFTL-APP#54]
Bitte um Informationen bezüglich diesem Punkt in der Doku.

**Comment by Patrick-Kunze** [comment]
Den Qualitätskontrollplan hatte ich SK zukommen lassen. Habe ihn nocheinmal an JS per Mail versandt

**Comment by Patrick-Kunze** [comment]
hier der Qualitätskontrollplan.

Am 08.07.2015 um 11:30 schrieb Jan Sutmöller:
